### ISSUE TITLE
Where to Deploy? 🤔

### ISSUE THREAD

**Issue by Viddesh1** [Ankita01K/Hindi-English-Alphabets-Recognition#1]
Hi @Ankita01K ,

Below are a few free platforms that I found for deploying your machine learning app ✨

1) https://render.com/
2) https://streamlit.io/cloud

Also, find a YouTube 🎥 video attached within :-

https://youtu.be/bXRVgg2iWyc?si=TgpDPRQgtEXAXwkF

Thanks!
Viddesh

**Comment by Ankita01K** [comment]
Hi Viddesh,

Thanks for sharing these free platforms for deploying machine learning apps! 
I'll definitely check them out. Also, I appreciate the YouTube video link for further guidance.

**Comment by Viddesh1** [comment]
Hello @Ankita01K ,

Interesting to see that this issue is still open.
Closing this issue now.

Regards!
Viddesh
